# Site settings
remote_theme : murraco/jekyll-theme-minimal-resume
title : "trial"
title_seperator : "_"
name : "HYUNJAM"
description : "null"
url: "whguswka.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Hyun Jam Jo
user_description: 
user_title: Statistician
email: whguswka@outlook.kr
# github_username:  whguswka

exclude: ['package.json', 'src' , 'node_modules']
